### ISSUE TITLE
Code availablity

### ISSUE THREAD

**Issue by MoulikChoraria** [YamingGuo98/FedIIR#1]
It's been a while since ICML, when do the authors plan to make the code public as claimed in their paper?

**Comment by ymguo21** [comment]
Thank you for inquiring about the release of our code. As a graduating master's student, I am currently heavily engaged in job applications and handling various interviews. It may take me longer than initially anticipated to organize and release the code. I kindly request your understanding and patience during this transitional period.

**Comment by MoulikChoraria** [comment]
Ah, no worries.

Best of luck for your applications, and great work in the paper.

Best,
Moulik
