### ISSUE TITLE
reproduce results

### ISSUE THREAD

**Issue by YAaNnGg** [YamingGuo98/FedIIR#2]
Hi! It is a great work! I've tried to reproduce the results, and while I have followed the parameters in the paper, I've encountered difficulties as my results do not align with those you published. In PACS, I got 92.6, 79.4, 77.9, and 81.8 for P, A, C, and S respectively, which are 94.2, 82.9, 75.8, and 81.9 in the paper. 

I suspect that there might be some parameters missing from my setup. For example, it's not mentioned in the paper about the specific hidden dims of the 2 fully connected layers at the end of Resnet.  Also, maybe the scheduler affects the training.

I would greatly appreciate it if you could share the code used in your experiments.  Will there be a schedule or plan for releasing the code? Alternatively, if possible, could you provide more detailed information on some crucial parameters or tricks that may not have been explicitly mentioned in the paper?

Thanks a lot.

**Comment by ymguo21** [comment]
The code has been made available. Concerning your question, I conjecture that one contributing factor could be the difference in the hidden dimensions of the fully connected layers. Another potential factor might be the absence of the exponential moving average (ema) technique, as described in Appendix C on page 14 of the paper. I appreciate your patience, and now you can use the latest code to attempt to reproduce the results.

**Comment by YAaNnGg** [comment]
Thank you so much for your prompt response and for open-sourcing the code.  It undoubtedly will help a lot in reproducing the results and for further work. Thanks again for your contribution!
